name: Deploy to Local Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 실행 권한 부여 및 빌드
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Docker 이미지 빌드
        run: |
          docker build -t my-spring-app .

      - name: Docker 이미지 압축
        run: |
          docker save my-spring-app | gzip > my-spring-app.tar.gz

      - name: 로컬 서버에 Docker 이미지 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.KYJ_LOCAL_SERVER_HOST }}
          username: ${{ secrets.KYJ_LOCAL_SERVER_USER }}
          port: ${{ secrets.KYJ_LOCAL_SERVER_PORT }}
          key: ${{ secrets.KYJ_SSH_PRIVATE_KEY }}
          source: "my-spring-app.tar.gz"
          target: "~/"

      - name: 로컬 서버에서 Docker 컨테이너 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KYJ_LOCAL_SERVER_HOST }}
          username: ${{ secrets.KYJ_LOCAL_SERVER_USER }}
          port: ${{ secrets.KYJ_LOCAL_SERVER_PORT }}
          key: ${{ secrets.KYJ_SSH_PRIVATE_KEY }}
          script: |
            docker load < ~/my-spring-app.tar.gz
            docker stop my-spring-app || true
            docker rm my-spring-app || true
            docker run -d --name my-spring-app \
              -p 8080:8080 \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
              -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
              -e GCP_SA_KEY_BASE64=${{ secrets.GCP_SA_KEY_BASE64 }} \
              -e JWT_KEY=${{ secrets.JWT_KEY }} \
              -e OPEN_API_KEY=${{ secrets.OPEN_API_KEY }} \
              -e GOOGLE_MAP_KEY=${{ secrets.GOOGLE_MAP_KEY }} \
              -e KAKAO_RESTAPI_KEY=${{ secrets.KAKAO_RESTAPI_KEY }} \
              -e NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} \
              -e NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} \
              -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              my-spring-app
