name: CI with MySQL Integration Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # (1) MySQL 컨테이너 설정
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password  # 루트 비밀번호
        ports:
          - 3306:3306
        # healthcheck 등 옵션을 세부적으로 줄 수도 있음
        # options: --health-cmd="mysqladmin ping -h localhost --silent"

    steps:
      # 1. 소스 체크아웃
      - name: Check out code
        uses: actions/checkout@v3

      # 2. JDK 설정 (예시: Java 17)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # 3. Gradle 빌드 & 통합테스트
      - name: Build with Gradle (Integration Test)
        run: |
          # (2) DB 접속 정보 환경변수 세팅
          export DB_URL="jdbc:mysql://127.0.0.1:3306/testdb?useSSL=false&characterEncoding=UTF-8"
          export DB_USERNAME="root"
          export DB_PASSWORD="password"

          # (3) testdb 생성
          mysql -h 127.0.0.1 -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS testdb"

          # (4) Gradle 실행 (테스트시 ENV VAR 사용)
          ./gradlew clean build
